pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                dir('08_cicd/jenkins') {
                    sh "docker build . -t myapp"
                }
            }
        }

        stage('Deploy') {
            steps {
                sh "docker run -d -p 8080:8080 --name myapp myapp"
            }
        }

        stage('Integration Test') {
            steps {
                sleep 30
                sh "curl http://localhost:8080 -f"
            }
        }
    }
}