pipeline {
    agent {
         node {
            label 'Built-In Node'
        }
    }

    stages {
        stage('Build') {
            steps {
                dir('08_cicd/jenkins') {
                    sh "docker build . -t myapp"
                }
            }
        }

        stage('Test') {
            steps {
                sh "echo 'Test myapp'"
            }
        }

        stage('Deploy') {
            steps {
                sh "docker run -d -p 8080:8080 myapp"
            }
        }
    }
}