---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml

driver:
  name: delegated

platforms:
  - name: molecule-linux-lamp-demo-web1
    aws_image_id: ami-0b0dcb5067f052a63 
    aws_region: us-east-1
    instance_type: t2.micro
    assign_public_ip: True
    groups:
      - webservers    

  - name: molecule-linux-lamp-demo-web2
    aws_image_id: ami-0b0dcb5067f052a63 
    aws_region: us-east-1
    instance_type: t2.micro
    assign_public_ip: True
    groups:
      - webservers    

  - name: molecule-linux-lamp-demo-dbserver
    aws_image_id: ami-0b0dcb5067f052a63 
    aws_region: us-east-1
    instance_type: t2.micro
    assign_public_ip: True
    groups:
      - dbservers    
 
provisioner:
  name: ansible
  log: true
  host_key_checking: False
  connection_options:
    ansible_connection: ssh

scenario:
  name: default

verifier:
  name: ansible

