---
# This playbook contains common plays that will be run on all nodes.

- name: Install ntp
  yum:
    name: ntp
    state: present
  tags: ntp

- name: Configure ntp file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  tags: ntp
  notify: Restart ntpd

- name: Start the ntp service
  service:
    name: ntpd
    state: started
    enabled: yes
  tags: ntp

- name: Get selinux status
  command: getenforce
  register: sestatus
  changed_when: false
