---
- hosts: all
  become: yes
  gather_facts: False

  tasks:
    - name: create users
      user:
        name: "{{ item }}"
        state: absent
      loop:
        - bobi
        - deyan
        - jesse
        - alex
        - ilir
        - daniel
        - pesho

    
  