---
- hosts: all
  become: yes
  ###############################################
  gather_facts: True
  ###############################################
  # ansible all -m setup -i inventory/

  vars:
    supported_os:
      - RedHat
      - Amazon

  tasks:
    - name: Install, configure, and start Apache
      block:
        - name: Install httpd and memcached
          yum:
            name:
            - httpd
            - memcached
            state: present
    
        - name: Start httpd service
          service:
            name: httpd
            state: started
            enabled: True
            
      when: ansible_facts['distribution'] in supported_os

      
