Vagrant.configure(2) do |config|

    config.vm.define "vm" do |server|
      server.vm.box = "generic/centos7"
      server.vm.hostname = "docker"
  
      server.vm.provider :libvirt do |libvirt|
        libvirt.memory = 1024
      end

      server.vm.provision "shell", privileged: true, inline: <<-SHELL
          yum update -y
          yum install wget git vim -y
          yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          yum install docker-ce docker-ce-cli containerd.io -y
          systemctl start docker
          systemctl enable docker
      SHELL
	  
    end
end
  