pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                dir('06_cicd/jenkins') {
                    sh "docker build . -t myapp"
                }
            }
        }

        stage('Deploy') {
            steps {
                sh "docker run -d -p 8080:8080 --name myapp myapp"
            }
        }
    }
}