Vagrant.configure(2) do |config|
  
    config.vm.define "centos8" do |server|
      server.vm.box = "generic/centos8"
      server.vm.hostname = "centos8.infra.local"
      server.vm.network "private_network", ip: "192.168.10.10"
  
      server.vm.provider :libvirt do |libvirt|
        libvirt.memory = 1024
      end
    end

    config.vm.define "windows2019" do |server|
      server.vm.box = "StefanScherer/windows_2019"
      server.vm.hostname = "windows2019.infra.local"
      server.vm.network "private_network", ip: "192.168.10.11"
  
      server.vm.provider :libvirt do |libvirt|
        libvirt.memory = 2048
      end
    end

end
  