---
- hosts: all
  become: yes
  gather_facts: True

  tasks:
    - debug:
        msg: "{{ ansible_facts['distribution'] }}"
    
    - debug:
        var: ansible_facts['distribution']
        
    - debug:
        var: ansible_facts
      debugger: always

         
  